### ISSUE TITLE
Reversed note type

### ISSUE THREAD

**Issue by crazko** [sobjornstad/TiddlyRemember#16]
Hi, just recently I came around your plugin, thanks for it! It's the perfect choice to extend notes in TiddlyWiki as stated in [these articles](https://notes.andymatuschak.org/z5ARNXtS5VxteskEW91S1yYTgAcLABNXsZuJE?stackedNotes=z4mAF1uBV96r72e4NjLcDaujEyTPGiUQJEj8C).

I'd like to ask, if it's possible to add a new note type which would behave like **basic reversed** type?

It would be a great addition to my workflow, but I don't know if it's something that's needed to be integrated into add-on or I can setup it manually in my Anki configuration.

Thanks.

**Comment by sobjornstad** [comment]
Needs a new macro and a few changes to the syncing process for good results (since no supported note types currently have multiple cards).

You could try to work around it by importing them as one-sided (Q&A) cards and then changing the note type in Anki, but this will break the link and you'll end up with duplicate cards if you sync again, unless you manually remove the notes from TiddlyWiki or edit them so they don't match the filter after the first sync, so that's probably not a great idea.

**Comment by crazko** [comment]
> You could try to work around it by importing them as one-sided (Q&A) cards and then changing the note type in Anki, but this will break the link and you'll end up with duplicate cards if you sync again, unless you manually remove the notes from TiddlyWiki or edit them so they don't match the filter after the first sync, so that's probably not a great idea.

Yeah, that seems like pretty tough workaround.

> Needs a new macro and a few changes to the syncing process for good results (since no supported note types currently have multiple cards).

I see. Maybe I could help with that if you are willing to add such feature into your add-on. I'd just need to test the local build.

**Comment by sobjornstad** [comment]
I threw something together. How does this draft look? Is “pair” a good term for this note type, and the 1/2 indicators instead of Q/A an understandable way of conveying that this is a two-sided note?

![pair-rendered](https://user-images.githubusercontent.com/2313414/94327820-106b2280-ff73-11ea-8936-8b5be442a3f3.png)
![pair-edit](https://user-images.githubusercontent.com/2313414/94327821-1234e600-ff73-11ea-9e68-f1ed2d736a07.png)
![anki](https://user-images.githubusercontent.com/2313414/94327815-0c3f0500-ff73-11ea-897e-19da5f5943b7.png)

**Comment by crazko** [comment]
I think 1/2 indicators are fine, but I'd suggest to go rather with `BasicReversed` name. ["Reverse"](https://docs.ankiweb.net#/templates/generation?id=reverse-cards) is a term used in Anki for such a note type and so should be more explanatory to the users.
Thanks for your work!

**Comment by sobjornstad** [comment]
Thanks for the feedback!

To be clear, `BasicPair`, as shown in the first two screenshots, is just the name of a tiddler in my wiki of test cases, not something that appears anywhere in TiddlyRemember's interface or documentation. The term used currently is just **pair note**.

I do like the idea of getting “reverse” or “reversed” in the name to match Anki, but I'm not sure I see a way to make it parallel with the names of the types of notes TR currently offers, which are “Question-and-answer notes” and “Cloze notes”. “Reverse notes” doesn't really work, because it's the *cards* that are reversed, not the notes themselves. (Anki never applies the adjective “reverse” to the note type itself – the manual link you provided discusses reversed *cards*, and the note type is titled `Basic (and reversed card)`.)

If you can think of a way around that, I'd love to hear it.

**Comment by crazko** [comment]
I see, thanks for the explanation. I'm pretty much new into Anki and, to be honest, I use terms card and note interchangeably. Which is surely not great, but only now I can see why is this happening - note type has _card_ in its name. That confused me.

Let's map Anki note types to your TiddlyRemember note types and see what can we derive:

|Anki|TiddlyRemember|
|-----|----|
|Cloze|Cloze notes|
|Basic|Question-and-answer notes|
|Basic (and reversed card)|**Reversed question-and-answer notes**|

Probably not that great as it's too long, but it follows both tools' conventions. But maybe let's not over-complicate it, **pair note** is good enough :)

**Comment by sobjornstad** [comment]
I think reversing a Q&A would yield an “answer-and-question” card, like you were on *Jeopardy!*. :-)

I agree, let's go with “pair note” and if it turns out to pose problems, not too big a deal to rename it later. I'll try to make the reverse aspect and the default note type it's related to clear in the documentation.

Notes and cards are irritating concepts because you can get away with using them interchangeably until suddenly you can't, which means many people never figure it out. The implication of `Basic (and reversed card)` is supposed to be that it's the basic note type (which generates one “forward” card) but also generates a reversed card. I can see how that's confusing though!

**Comment by sobjornstad** [comment]
Released in 1.2. Let me know if you have any further questions or issues.
