### ISSUE TITLE
Multiple occlusions in inline cloze do not sync

### ISSUE THREAD

**Issue by crazko** [sobjornstad/TiddlyRemember#17]
Syncing is not working for inline cloze deletion with multiple occlusions defined, like in this example:

```
<<remembercz "20200906204435482"
  "Platformy zdieľanej ekonomiky znižujú transakčné náklady na {c1::dohľadávanie}, {c2::dohadovanie} a {c3::dodržanie dohody}." inline>>
```

Without `inline` attribute, syncing works properly and three cards are created.

**Comment by sobjornstad** [comment]
This will be fixed in the next release. In the meantime, if you click *View Files* in the Anki add-ons dialog with TiddlyRemember selected and change line 268 of `twnote.py`, you should be able to get it working. Original:

```
        return bool(soup.find("div", class_="remembercz"))
```

New:

```
        return bool(soup.find(class_="remembercz"))
```

Be sure to keep the indentation the same. When done, save the file, restart Anki, and try again.

Alternatively, if there is at least one block cloze in the tiddler as well, it should work (though I haven't tested that).

**Comment by crazko** [comment]
> **Edit**: Just to be sure, by "syncing is not working," you mean the note just doesn't show up in Anki, right? Just want to make sure we aren't looking at different bugs. :)
 
Yes, exactly :) thanks.
