### ISSUE TITLE
Improvement request: only sync tiddlers with a 'lastmodified' date  that is more recent than the last sync

### ISSUE THREAD

**Issue by ldorigo** [sobjornstad/TiddlyRemember#37]
I have a very large wiki that contains all my notes from several years of university. Currently, syncing to Anki takes around 3-5 minutes, and sends my laptop fan spinning like crazy. 

Would it be possible to add a setting that allows only syncing tiddlers that have been modified since the last sync, as well as new tiddlers? This should dramatically reduce the amount of tiddlers that need to be rendered (and thus improve performance)

Keep up the great work, this plugin has tremendously improved my learning experience !

**Comment by sortega** [comment]
Just curious, how many tiddlers do you have in your wiki?

**Comment by sortega** [comment]
Maybe you can reduce the time it takes to sync by changing the filter used by the Anki plugin. By default it is `[type[text/vnd.tiddlywiki]] [type[]] +[!is[system]]` but you can be more restrictive. Maybe you can use some tags or a cutoff date.

However, be **extremely careful** because if you exclude tiddlers with questions, those will be wiped out of anki. I recommend you to backup you collection before trying changes.

**Comment by sobjornstad** [comment]
I don't think a date cutoff could be made to work reliably without completely rearchitecting TiddlyRemember (and making it less flexible), because there is not a one-to-one correspondence between the tiddler on which a TiddlyRemember note is placed and the data within that note. A tiddler can, for instance, transclude data from another tiddler into the `remember*` macros, and TiddlyRemember's syncer has no way of figuring out where that data came from and thus where it would need to look for a modified date (it would basically have to reimplement the wikitext parser, with some additional features to track the provenance of every bit of wikitext, to pull that off).

I'm also interested in what your wiki is like. I have a wiki with thousands of tiddlers and it syncs in an entirely reasonable amount of time (probably less than 15 seconds). I have experienced problems where it takes forever when binary files, images, etc. end up in the hopper, though, so I'm wondering if that's really what's going on here. I haven't looked too closely into the cause of that because it was really easy to exclude them with the filter in my test.

**Comment by ldorigo** [comment]
I have approx 5.000 tiddlers, of which approx. 2500 are binary files (or associated meta files). This includes around 500 pdf files which can be quite large. But the default filter seems to exclude those, so I'm not sure why they would slow things down?

(note that I'm currently working on a 10 year old laptop, so 15 seconds on a fast new computer could reasonably translate to 2-3 minutes.)

**Comment by ldorigo** [comment]
So, I timed it, and it seems like most of the time is actually spent *before* the progress bar starts counting. 

It took 50 seconds before numbers appeared on the progress bar, and 30 seconds after that (I closed everything else for this test, which explains that it was faster - it takes at least double the time with a normal cpu load).

**Comment by sobjornstad** [comment]
> But the default filter seems to exclude those, so I'm not sure why they would slow things down?

Correct, it *shouldn't*, but we all know *should* and *does* are different things in IT :). Are you transcluding those PDFs/images/etc into some of the tiddlers that you're rendering with TiddlyRemember? Though I wouldn't really expect that to make a difference.

Also, are your tiddlers possibly making really heavy use of macros or transclusions or anything like that? Just trying to figure out what might cause the rendering component of the sync to take longer than usual.

> So, I timed it, and it seems like most of the time is actually spent before the progress bar starts counting.

That's expected. The first stage is that TW running on Node.js renders the tiddlers, and it doesn't provide any progress as it does. Then TiddlyRemember picks up with extracting the contents of those rendered tiddlers, and it's able to provide a count on this. The first step is usually quite a bit slower in my experience.

One other thing -- I'm guessing you're using a folder wiki directly on your computer, with the "Folder" option chosen in the syncing settings? If the files are large, a download from a URL or extract from a file wiki could take significant additional time. But since you were talking about meta tiddlers and you do have so many files, I'm assuming you're already using a folder wiki.

> (note that I'm currently working on a 10 year old laptop, so 15 seconds on a fast new computer could reasonably translate to 2-3 minutes.)

This seems possible. I can try on my old Windows laptop this evening and see what the speed factor is to my main development machine.

If the cause is just that your computer is old, and none of the earlier notes apply to your situation, I'm afraid I don't have any ideas for you to speed it up, aside from sortega's suggestion of trying to limit the set of tiddlers you need to search for TR notes (even something as simple as searching for the word `remember` on tiddlers might work OK here, as long as you don't have custom macros that would result in the word `remember` not showing up in your wikitext).  As noted in my earlier comment, I don't think a sync-only-changed-tiddlers approach is workable.

**Comment by ldorigo** [comment]
> Also, are your tiddlers possibly making really heavy use of macros or transclusions or anything like that? 

Virtually all of my tiddlers contain a "table of contents" that lists tiddler below them in the content hierarchy, it's done by transcluding the following template tiddler:

```
<div class="tc-table-of-contents">
<<toc-selective-expandable $(currentTiddler)$ sort[created]>>
</div>
```
and I use it by adding {{||tocsel}} wherever I want it to appear. Could this be the problem?

> This seems possible. I can try on my old Windows laptop this evening and see what the speed factor is to my main development machine.

I am back home now and have access to my much newer and faster desktop, so I can also time it - before I do so, can you confirm that syncing the same wiki folder (I have it on dropbox and synced on both computers) to the same anki collection (shared via anki's built-in cloud sharing) on two different computers won't incur any loss of data?

**Comment by sobjornstad** [comment]
> Could this be the problem?

Maybe? I'm not sure how intensive the TOC macros are. You could try blanking the template tiddler temporarily to see what impact it has.

> can you confirm that syncing the same wiki folder (I have it on dropbox and synced on both computers) to the same anki collection (shared via anki's built-in cloud sharing) on two different computers won't incur any loss of data?

I haven't tried it, but I can't think of any reason why it would. If you're concerned, just restart Anki or sync to AnkiWeb before trying, then watch the balloon that appears briefly in the lower-left and indicates what changes have been made. If it does something wrong, you can [restore an automatic backup of your Anki collection](https://docs.ankiweb.net/#/files?id=backups) (this is why you restart/sync first, to take a backup).

**Comment by sobjornstad** [comment]
Results of my test: 11 seconds to sync on my development machine, 29 seconds to sync on my 8-year-old laptop, with 2300  tiddlers matching the filter. Didn't close out of anything on either machine, on both a few things open but not actively doing much. And data was on a FreeNAS fileserver (presumably in the RAM cache as I am constantly hitting the wiki files) over gigabit Ethernet for both machines.

My 8-year-old laptop was fairly nice when it was new, but even so I'm somewhat doubtful yours is almost 3 times slower under zero load without some other factor involved.

**Comment by sobjornstad** [comment]
@ldorigo: Any updates on this? I don't think the improvement requested in the title is possible, but if there are other things I can do to improve performance for you I'd be happy to think about them.
